# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rugbypy',
                'doc_host': 'https://seanyboi.github.io',
                'git_url': 'https://github.com/seanyboi/rugbypy',
                'lib_path': 'rugbypy'},
  'syms': { 'rugbypy.core': {'rugbypy.core.foo': ('fetch_match_stats.html#foo', 'rugbypy/core.py')},
            'rugbypy.fetch_match_stats': { 'rugbypy.fetch_match_stats.fetch_match_details': ( 'fetch_match_stats.html#fetch_match_details',
                                                                                              'rugbypy/fetch_match_stats.py'),
                                           'rugbypy.fetch_match_stats.fetch_matches': ( 'fetch_match_stats.html#fetch_matches',
                                                                                        'rugbypy/fetch_match_stats.py')},
            'rugbypy.fetch_player_stats': { 'rugbypy.fetch_player_stats.fetch_player_stats': ( 'fetch_player_stats.html#fetch_player_stats',
                                                                                               'rugbypy/fetch_player_stats.py')},
            'rugbypy.fetch_team_stats': { 'rugbypy.fetch_team_stats.fetch_team_stats': ( 'fetch_team_stats.html#fetch_team_stats',
                                                                                         'rugbypy/fetch_team_stats.py')}}}
