# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rugbypy',
                'doc_host': 'https://seanyboi.github.io',
                'git_url': 'https://github.com/seanyboi/rugbypy',
                'lib_path': 'rugbypy'},
  'syms': { 'rugbypy.core': {'rugbypy.core.foo': ('fetch_match_stats.html#foo', 'rugbypy/core.py')},
            'rugbypy.fetch_match_stats': { 'rugbypy.fetch_match_stats.say_hello': ( 'fetch_match_stats.html#say_hello',
                                                                                    'rugbypy/fetch_match_stats.py')}}}
