# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/fetch_player_stats.ipynb.

# %% auto 0
__all__ = ['fetch_player_stats']

# %% ../nbs/fetch_player_stats.ipynb 3
def fetch_player_stats(player_id: str):
    "Fetches player stats for a particular player"
    return f"{player_id}"
