# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/fetch_match_stats.ipynb.

# %% auto 0
__all__ = ['fetch_all_matches_on_date']

# %% ../nbs/fetch_match_stats.ipynb 4
def fetch_all_matches_on_date(date: str):
    "Fetches all rugby matches on a particular date."
    return f"{date}"
