# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/fetch_team_stats.ipynb.

# %% auto 0
__all__ = ['fetch_team_stats']

# %% ../nbs/fetch_team_stats.ipynb 3
def fetch_team_stats(date: str):
    "Fetches team stats from a particular game."
    return f"{date}"
