"""Fetch team stats for individual games."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/team.ipynb.

# %% auto #0
__all__ = ['fetch_all_teams', 'fetch_team_stats']

# %% ../nbs/team.ipynb #ff36e074
import pandas as pd
import typing

# %% ../nbs/team.ipynb #e6d0059f
def fetch_all_teams():
    """
    Fetches all team available
    """
    try:
        print("Fetching all teams available...")
        team_url = "https://github.com/seanyboi/rugbydata/blob/main/data/v3/team/team_registry.parquet?raw=true"
        team_stats = pd.read_parquet(team_url, engine="pyarrow")
        return team_stats
    except Exception as _:
        print("No teams available. Please raise an issue!")

# %% ../nbs/team.ipynb #77a32690
def fetch_team_stats(
    team_id: str,
    date: typing.Optional[str] = None,
    match_id: typing.Optional[str] = None,
) -> pd.DataFrame:
    """
    Fetches team statistics for a specific team with optional filtering. \n
    Returns all stats by default, or filters by date, match, or competition when specified. \n
    Only one optional filter parameter should be provided at a time. \n

    Args:
        team_id (str): The unique identifier for the team
        date (typing.Optional[str]): Filter by game date in YYYYMMDD format (default: None)
        match_id (typing.Optional[str]): Filter by specific match identifier (default: None)
        competition_id (typing.Optional[str]): Filter by competition identifier (default: None)

    Returns:
        pd.DataFrame: Team statistics, filtered if optional parameter provided,
                     or all stats if no filter specified
    """
    try:
        team_url = f"https://github.com/seanyboi/rugbydata/blob/main/data/v3/team/{team_id}.parquet?raw=true"
        team_stats = pd.read_parquet(team_url, engine="pyarrow")

        if date:
            print(f"Fetching team stats for team_id: {team_id} on date: {date}...")
            team_stats = team_stats.query("game_date == @date")
        elif match_id:
            print(
                f"Fetching team stats for team_id: {team_id} in match_id: {match_id}..."
            )
            team_stats = team_stats.query("match_id == @match_id")
        else:
            print(f"Fetching all team stats for team_id: {team_id}...")

        return team_stats

    except Exception as _:
        print(
            f"No team stats for {team_id} because the team id does not exist. Please raise an issue!"
        )
